name: Deploy to Azure VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    # Build Frontend
    - name: Build Frontend
      run: |
        cd frontend
        npm install
        npm run build

    # Build Backend
    - name: Build Backend
      run: |
        cd backend
        npm install

    # Deploy to Azure VM
    - name: Copy files to VM
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.AZURE_VM_HOST }}
        username: win10
        key: ${{ secrets.AZURE_VM_SSH_KEY }}
        source: "backend/,frontend/dist/"
        target: "/home/win10/oneWeekReportWeb"
        strip_components: 0

    - name: Deploy Application
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.AZURE_VM_HOST }}
        username: win10
        key: ${{ secrets.AZURE_VM_SSH_KEY }}
        script: |
          # Copy frontend files to nginx directory
          sudo cp -r /home/win10/oneWeekReportWeb/frontend/dist/* /var/www/html/
          
          # Start backend with PM2
          cd /home/win10/oneWeekReportWeb/backend
          npm install
          pm2 delete oneWeekReport-backend || true
          pm2 start bin/www --name oneWeekReport-backend
          
          # Save PM2 process list
          pm2 save
          
          # Configure PM2 to start on boot
          pm2 startup | tail -n 1 | bash
